const http=require('http'),fs=require('fs'),path=require('path');
const PORT=process.env.PORT||3000;
const key=process.env.OPENAI_API_KEY;
const mime={'.html':'text/html','.js':'text/javascript','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{
 if(req.url==='/api/health'){return send(res,200,{ok:true,aiConfigured:!!key})}
 if(req.url==='/api/tts' && req.method==='POST'){
  let body='';req.on('data',c=>body+=c);req.on('end',async()=>{try{const data=JSON.parse(body);if(!data.text)return send(res,400,{error:'text required'});if(!key)return send(res,200,{configured:false});const r=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts',voice:data.voice||'nova',input:data.text,instructions:data.instructions||'Speak like a natural human conversation partner. Use subtle emotion, realistic pauses, varied sentence rhythm, clear pronunciation, and a gentle conversational pace. Do not sound robotic or overly dramatic.'})});if(!r.ok)throw Error('TTS request failed');const audio=Buffer.from(await r.arrayBuffer()).toString('base64');send(res,200,{configured:true,audio:'data:audio/mpeg;base64,'+audio})}catch(e){send(res,500,{error:e.message})}});return}
 if(req.url==='/api/chat' && req.method==='POST'){
  let body='';req.on('data',c=>body+=c);req.on('end',async()=>{try{const data=JSON.parse(body);if(!data.message)return send(res,400,{error:'message required'});if(!key)return send(res,200,{reply:'Great effort! I understood you. Try saying that once more in a complete sentence.',configured:false});const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4o-mini',temperature:.4,messages:[{role:'system',content:'You are a kind English speaking coach for a learner who understands English but struggles to speak. Reply in exactly this format: Encouragement: one short sentence. Correction: one important grammar or word correction, or say No correction needed. Natural sentence: one improved sentence. Fluency tip: one practical speaking tip. Do not correct every mistake. Keep the total under 80 words.'},{role:'user',content:data.message}]})});const j=await r.json();if(!r.ok)throw Error(j.error?.message||'AI request failed');send(res,200,{reply:j.choices[0].message.content,configured:true})}catch(e){send(res,500,{error:e.message})}});return}
 let file=req.url==='/'?'/english-speaking-coach.html':req.url;let p=path.join(__dirname,file);if(!p.startsWith(__dirname)||!fs.existsSync(p))return send(res,404,{error:'not found'});res.writeHead(200,{'Content-Type':mime[path.extname(p)]||'text/plain'});fs.createReadStream(p).pipe(res);
});function send(res,status,obj){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(obj))}server.listen(PORT,'0.0.0.0',()=>console.log(`SpeakEasy server running on ${PORT}`));